import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

let hash = 'dev';
try {
  hash = execSync('git rev-parse --short=6 HEAD', { encoding: 'utf8' }).trim();
} catch {}

const out = join(dirname(fileURLToPath(import.meta.url)), '../src/git-hash.ts');
writeFileSync(out, `// Auto-generated by scripts/gen-version.mjs — do not edit\nexport const GIT_HASH = '${hash}';\n`);
console.log(`[gen-version] ${hash}`);
